// BelRAI scoring scale / screener codes, used as Observation.code (BeScoreResult).
// Generated from common_translations_3.2.0.json by generate_codesystems.py.
// Do not edit by hand - re-run the script to regenerate.
// One code per scoring scale/screener (the question 'head').
// Surfaced to BeVSScore via the BeVSBelraiScore value set.

CodeSystem: BeCSBelraiScore
Id: be-cs-belrai-score
Title: "BelRAI Score Code System"
Description: "Codes identifying each BelRAI scoring scale/screener, used as Observation.code."
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #aHSDELIRIUM "Delirium Screener (aHSDELIRIUM)"
* #aHSDEMENTIA "Dementia Screener (aHSDEMENTIA)"
* #aHSDEPRESSION "Depression Screener (aHSDEPRESSION)"
* #aHSNUTRITION "Nutrition Screener (aHSNUTRITION)"
* #aMAPLE "Method for Assigning Priority Levels (aMAPLe)"
* #cABUSE "Mishandeling/Verwaarlozing"
* #cACTIV "Activiteiten"
* #cADD "Tabak- en alcoholgebruik"
* #cADL "Activiteiten van het dagelijks leven (ADL)"
* #cBEHAV "Gedrag"
* #cBOWEL "Darmproblemen"
* #cBRITSU "Mantelzorg"
* #cCARDIO "Hart en ademhaling"
* #cCOGNIT "Cognitieverlies"
* #cCOMMUN "Communicatie"
* #cDEHYD "Dehydratatie"
* #cDELIR "Delirium"
* #cDENTISTREFER "Doorverwijzing naar de tandarts"
* #cDRUG "Juist en verantwoord medicatiegebruik"
* #cENVIR "Thuisomgeving"
* #cFALLS "Valincidenten"
* #cFEEDTB "Sondevoeding"
* #cHSBEHAV "Gedrag - Ziekenhuis"
* #cHSCOGNIT "Cognitieverlies - Ziekenhuis"
* #cHSCOMMUN "Communicatie - Ziekenhuis"
* #cHSDEPRESS "Depressie - Ziekenhuis"
* #cHSFALLS "Valincidenten - Ziekenhuis"
* #cHSINSTITUTION "Kans op opname in een voorziening - Ziekenhuis"
* #cHSPAIN "Pijn - Ziekenhuis"
* #cHSREADMISSION "Kans op heropname"
* #cHSUNDERNUTRITION "Ondervoeding - Ziekenhuis"
* #cIADL "Instrumentele activiteiten van het dagelijks leven (IADL)"
* #cMHCRIM "Criminele activiteiten"
* #cMHCTRLINT "Vrijheidsbeperkende maatregelen"
* #cMHEDEMP "Opleiding en werk"
* #cMHEXER "Beweging"
* #cMHFINAN "Persoonlijke financiën"
* #cMHHARMOTH "Schade aan anderen"
* #cMHINFSUPP "Mantelzorg - Mentale gezondheid"
* #cMHIPCON "Intermenselijke conflicten"
* #cMHMEDMGT "Geneesmiddelenbeheer en therapietrouw"
* #cMHPAIN "Pijn - Mentale gezondheid"
* #cMHREHOSP "Heropname"
* #cMHSELFCR "Zelfzorg"
* #cMHSELFHA "Zelfmoordgedrag en opzettelijke zelfverwonding"
* #cMHSLEEP "Slaapstoornissen - Mentale gezondheid"
* #cMHSMOKE "Roken"
* #cMHSOCREL "Sociale relaties - Mentale gezondheid"
* #cMHSSDIS "Ondersteuningskader bij ontslag"
* #cMHSUBUSE "Middelengebruik"
* #cMHTRAUMA "Traumatische levensgebeurtenissen"
* #cMHWTMGT "Gewichtsmanagement"
* #cMOOD "Stemming"
* #cNUTR "Ondervoeding"
* #cORALHYG "Mondhygiëne"
* #cPACTIV "Bevordering van de lichaamsbeweging"
* #cPAIN "Pijn"
* #cPCDYS "Dyspneu"
* #cPCFATIG "Vermoeidheid"
* #cPCMOOD "Stemming-Palliative Care"
* #cPCNUTR "Voeding - Palliatieve zorg"
* #cPCPAIN "Pijn - Palliatieve zorg"
* #cPCSLEEP "Slaapstoornis - Palliatieve zorg"
* #cPULCER "Decubitus"
* #cRESTR "Fysieke fixatie"
* #cRISK "Kans op opname in een voorziening"
* #cSOCFUNC "Sociale omgang"
* #cURIN "Urine-incontinentie"
* #cpHSADL "Activiteiten van het dagelijks leven (ADL)- Preventie"
* #cpHSDELIRIUM "Delirium - Preventie"
* #cpHSPULCER "Decubitus - Ziekenhuis"
* #cpcPUIMP "Decubitus - Palliatieve zorg"
* #ctHSADL "Activiteiten van het dagelijks leven (ADL)- Behandeling"
* #ctHSDELIRIUM "Delirium - Behandeling"
* #ctHSPULCER "Decubitus - Behandeling - Ziekenhuis"
* #rHSADL "Risk of Adverse Outcomes in the Form of ADL Decline in Hospital (rHSADL)"
* #rHSDELIRIUM "Risk of Delirium in Hospital (rHSDELIRIUM)"
* #rHSFALLS "Falls Risk in Hospital (rHSFALLS)"
* #rHSPULCER "Pressure Ulcer Risk Scale in Hospital (rHSPULCER)"
* #rHSREADMISSION "Risk of Readmission in Hospital (rHSREADMISSION)"
* #sABS "Aggressive Behaviour Scale (sABS)"
* #sADLH "ADL Hierarchy Scale (sADLH)"
* #sBMI "Body Mass Index (sBMI)"
* #sCAGE "Addictions and Substance Use Scale (sCAGE)"
* #sCHESS "Changes in Health, End-stage Disease and Symptoms and Signs Scale (sCHESS)"
* #sCOMM "Communication Scale (sCOMM)"
* #sCPS "Cognitive Performance Scale (sCPS)"
* #sCPS2 "Cognitive Performance Scale 2 (sCPS2)"
* #sDRS "Depression Rating Scale (sDRS)"
* #sDbSI "Deafblind Severity Index (sDbSI)"
* #sFRAILTY "Frailty Scale (sFrailty)"
* #sHSADLH "ADL Hierarchy Scale – Hospital (sHSADLH)"
* #sHSPAIN "Pain Scale - Hospital (sHSPAIN)"
* #sHSPURS "Pressure Ulcer Risk Scale - Hospital (sHSPURS)"
* #sIADLCH "IADL Capacity Hierarchy Scale (sIADLCH)"
* #sPAIN "Pain Scale (sPAIN)"
* #sPURS "Pressure Ulcer Risk Scale (sPURS)"
* #sSRMOOD "Self-reported Mood Scale"
