Logical: BeModelEncounter
Title: "BeEncounter Model"
Description: "Administrative recording of a meeting between a patient and a practitioner/organisation, with references to clinical data."
Id: BeModelEncounter

* identifier 1..* Identifier "Unique business identifier of the CareSet"
* recordedDate 1..1 dateTime "Date of registration by the Author/Recorder (date of the last update)." "Date of registration by the Author/Recorder (date of the last update). Enables CareSet history management through the pair Business Identifier - RecordedDate, which guarantees access to the latest version of the content"
* author 1..1 Reference "The health professional who takes responsibility for the recorded content"
* status 1..1 code "Registration status, the moment in the lifecycle. For example: final, corrected, cancelled, entered-in-error. ValueSet: VS_Encounter_Status"
* class 0..* CodeableConcept "Classification of the type of Encounter. ValueSet: VS_Encounter_Class"
* serviceType 0..* CodeableConcept "Type of services/specialisation offered during the Encounter. ValueSet: VS_Encounter_ServiceType (see proposal VS_Be_ServiceType_Voorstel)"
* subject 1..1 Reference "The person who is the subject of the healthcare the record (CareSet) refers to. Refers to BePatient"
* episodeOfCare 0..* Reference "Reference to the EpisodeOfCare resource this Encounter is linked to. Refers to BeEpisodeOfCare"
* basedOn 0..* Reference "The request that initiated this Encounter. In this case it can only originate from BeCarePlan"
* careTeam 0..* Reference "Reference to the CareTeam resource recording which team is involved in the care during this Encounter. Refers to BeCareTeam"
* partOf 0..1 Reference "Reference to another Encounter this Encounter is part of. Refers to BeEncounter"
* serviceProvider 0..1 Reference "Organisation responsible for this Encounter. Refers to BeOrganization"
* participant 0..* BackboneElement "List of participants involved in the care during this Encounter. Refers to BePractitioner"
  * period 1..1 Period "Period during which the Participant is involved in this Encounter"
  * role 1..1 CodeableConcept "Role of the Participant involved in this Encounter"
* actualPeriod 0..1 Period "The effective start and end moments of this Encounter"
* length 0..1 Duration "Effective duration of the Encounter (excluding absences)"
* reason 0..* CodeableConcept "The list of Reasons that will be discussed during this Encounter. ValueSet: VS_Encounter_Reason"
* diagnosis 0..* Reference "List of diagnoses relevant for this Encounter. Refers to BeProblem"
* admission 0..1 BackboneElement "Details about the admission of the patient to the care organisation"
  * origin 0..1 Reference "The location the patient came from for the admission. Refers to BeOrganization"
  * admitSource 0..1 CodeableConcept "How the patient was admitted. ValueSet: VS_Encounter_Admission_AdmitSource"
  * reAdmission 0..1 boolean "Is this a re-admission of the patient?"
  * destination 0..1 Reference "Destination of the patient after discharge. Refers to BeOrganization"
  * dischargeDisposition 0..1 CodeableConcept "Category of location after discharge of the patient. ValueSet: VS_Encounter_Admission_DischargeDisposition"
* note 0..* Annotation "Additional information related to the CareSet content in free text form"
